# Generated by Django 6.0.4 on 2026-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verification_question',
            field=models.TextField(blank=True, help_text="Ask a specific question to verify the owner (e.g., 'What color is the case?')"),
        ),
    ]
